[plugins]
avro = { id = "com.github.davidmc24.gradle.plugin.avro", version = "1.9.1" }
versions = { id = "se.ascp.gradle.gradle-versions-filter", version = "0.1.16" }
license = { id = 'com.github.jk1.dependency-license-report', version = '3.0.1' }

[versions]
jackson-version = "2.20.1"
jupiter-version = "6.0.1"
ktor-version = "3.3.3"
navfelles-token-version = "5.0.30"
prometheus-version = "0.16.0"
testcontainer-version = "1.21.3"
tjenestespesifikasjoner-version = "1.1436e29"
rapidsandrivers-version = "2025081112301754908236.47b364d7b14c" # OBS! tbdlibs brukes av denne. De bør stemme overens
tbdlibs-version = "2025.08.16-09.21-71db7cad" # OBS! rapidsandrivers bruker denne. De bør stemme overens

[libraries]
cache-caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.2.3" }

database-hikaricp = { module = "com.zaxxer:HikariCP", version = "7.0.2" }
database-flywaydb = { module = "org.flywaydb:flyway-core", version = "11.18.0" }
database-flywaydbpostgres = { module = "org.flywaydb:flyway-database-postgresql", version = "11.18.0" }
database-postgresql = { module = "org.postgresql:postgresql", version = "42.7.8" }
database-kotliquery = { module = "com.github.seratch:kotliquery", version = "1.9.1" }

jackson-datatypejsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-version" }
jackson-datatypejdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson-version" }
jackson-modulekotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-version" }

kafka-clients = { module = "org.apache.kafka:kafka-clients", version = "4.1.1" }
kafka-avro = { module = "org.apache.avro:avro", version = "1.12.1" }
kafka-avroserializer = { module = "io.confluent:kafka-avro-serializer", version = "7.6.0" }

klage-kodeverk = { module = "no.nav.klage:klage-kodeverk", version = "1.12.17" }

kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version = "2.1.0" }

pdf-pdfbox = { module = "org.apache.pdfbox:pdfbox", version = "3.0.6" }

ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor-version" }
ktor-clientcore = { module = "io.ktor:ktor-client-core", version.ref = "ktor-version" }
ktor-clientloggingjvm = { module = "io.ktor:ktor-client-logging-jvm", version.ref = "ktor-version" }
ktor-clientauth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor-version" }
ktor-servercorejvm = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-doublereceive = { module = "io.ktor:ktor-server-double-receive", version.ref = "ktor-version" }
ktor-servercio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor-version" }
ktor-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor-version" }
ktor-servercontentnegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-version" }
ktor-clientcontentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor-version" }
ktor-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor-version" }
ktor-calllogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor-version" }
ktor-callid = { module = "io.ktor:ktor-server-call-id", version.ref = "ktor-version" }
ktor-statuspages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor-version" }
ktor-metricsmicrometer = { module = "io.ktor:ktor-server-metrics-micrometer", version.ref = "ktor-version" }
ktor-mustache = { module = "io.ktor:ktor-server-mustache", version.ref = "ktor-version" }
ktor-clientmock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor-version" }
ktor-server = { module = "io.ktor:ktor-server", version.ref = "ktor-version" }
ktor-serverresources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor-version" }
ktor-servertests = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor-version" }
ktor-serverswagger = { module = "io.ktor:ktor-server-swagger", version.ref = "ktor-version" }
ktor-webjars = { module = "io.ktor:ktor-server-webjars", version.ref = "ktor-version" }

etterlatte-common = { module = "pensjon-etterlatte-felles:common", version = "2025.11.10-14.35.6c85e2f202a7" }
teamdokumenthandtering-avroschemas = { module = "no.nav.teamdokumenthandtering:teamdokumenthandtering-avro-schemas", version = "1.1.6" }
brevbaker-api-model-common = { module = "no.nav.pensjon.brevbaker:brevbaker-api-model-common", version = "2.7.0"}

logging-slf4japi = { module = "org.slf4j:slf4j-api", version = "2.0.17" }
logging-logbackclassic = { module = "ch.qos.logback:logback-classic", version = "1.5.21" }
logging-logstashlogbackencoder = { module = "net.logstash.logback:logstash-logback-encoder", version = "8.1" }

metrics-micrometer-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version = "1.16.0" }
metrics-prometheus-simpleclientcommon = { module = "io.prometheus:simpleclient_common", version.ref = "prometheus-version" }
metrics-prometheus-simpleclienthotspot = { module = "io.prometheus:simpleclient_hotspot", version.ref = "prometheus-version" }

messaginghub-pooled-jms = { module = "org.messaginghub:pooled-jms", version = "3.1.7" }

mq-jakarta-client = { module = "com.ibm.mq:com.ibm.mq.jakarta.client", version = "9.4.4.0" }

navfelles-rapidsandriversktor = { module = "com.github.navikt:rapids-and-rivers", version.ref = "rapidsandrivers-version" }
navfelles-tjenestespesifikasjoner-avstemming = { module = "com.github.navikt.pensjon-etterlatte-tjenestespesifikasjoner:avstemming-v1-tjenestespesifikasjon", version.ref = "tjenestespesifikasjoner-version" }
navfelles-tjenestespesifikasjoner-oppdragsbehandling = { module = "com.github.navikt.pensjon-etterlatte-tjenestespesifikasjoner:nav-virksomhet-oppdragsbehandling-v1-meldingsdefinisjon", version.ref = "tjenestespesifikasjoner-version" }
navfelles-tjenestespesifikasjoner-oppdragsimulering = { module = "com.github.navikt.pensjon-etterlatte-tjenestespesifikasjoner:nav-system-os-simuler-fp-service-tjenestespesifikasjon", version.ref = "tjenestespesifikasjoner-version" }
navfelles-tjenestespesifikasjoner-tilbakekreving = { module = "com.github.navikt.pensjon-etterlatte-tjenestespesifikasjoner:tilbakekreving-v1-tjenestespesifikasjon", version.ref = "tjenestespesifikasjoner-version" }
navfelles-tokenclientcore = { module = "no.nav.security:token-client-core", version.ref = "navfelles-token-version" }
navfelles-tokenvalidationktor = { module = "no.nav.security:token-validation-ktor-v3", version.ref = "navfelles-token-version" }
navfelles-mockoauth2server = { module = "no.nav.security:mock-oauth2-server", version = "3.0.1" }

test-navfelles-rapidsandriversktor = { module = "com.github.navikt.tbd-libs:rapids-and-rivers-test", version.ref = "tbdlibs-version" }
test-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jupiter-version" }
test-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jupiter-version" }
test-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jupiter-version" }
test-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
test-kotest-assertionscore = { module = "io.kotest:kotest-assertions-core", version = "6.0.7" }
test-mockk = { module = "io.mockk:mockk", version = "1.14.6" }
test-testcontainer-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainer-version" }
test-testcontainer-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainer-version" }
test-testcontainer-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainer-version" }

commons-compress = { module = "org.apache.commons:commons-compress", version = "1.28.0" }
unleash-client = { module = "io.getunleash:unleash-client-java", version = "11.1.1" }

[bundles]
jackson = ["jackson-datatypejsr310", "jackson-datatypejdk8", "jackson-modulekotlin"]
